import { ensureApiSuccess } from "./localization.ts";

export interface GovernanceIdentity { readonly tenantId: string; readonly userId: string }
export type Confidentiality = "GeneralProject" | "RestrictedManagement" | "ConfidentialHse" | "CommercialSensitive";
export type Severity = "Low" | "Medium" | "High" | "Critical";
export type Urgency = "Routine" | "Soon" | "Immediate";
export type RiskStatus = "Proposed" | "Assessed" | "Active" | "Monitoring" | "Materialized" | "Expired" | "Closed" | "Reopened";
export type IssueStatus = "Open" | "UnderAssessment" | "ResponseInProgress" | "PendingVerification" | "Resolved" | "Closed" | "Reopened" | "NotAnIssue" | "Void";
export type DecisionRequestStatus = "Draft" | "ReadyForDecision" | "InDecision" | "MoreInformationRequired" | "Decided" | "Implementing" | "EffectReviewed" | "Closed" | "Withdrawn";
export type DeadlineSignal = "OnTrack" | "DueSoon" | "Overdue" | "EscalationDue";

export interface RiskMatrixModel { readonly id: string; readonly version: number; readonly title: string; readonly formulaVersion: string; readonly lowMaximum: number; readonly moderateMaximum: number; readonly highMaximum: number; readonly effectiveFrom: string }
export interface SlaRuleModel { readonly id: string; readonly version: number; readonly title: string; readonly entityType: "Issue" | "Risk" | "DecisionRequest"; readonly severity: Severity | null; readonly duration: number; readonly durationUnit: "ElapsedHours" | "ProjectWorkingDays"; readonly warningLeadMinutes: number; readonly escalationDelayMinutes: number; readonly escalationRecipientUserId: string; readonly escalationRecipientDisplayName: string; readonly effectiveFrom: string }
export interface GovernancePersonModel { readonly userId: string; readonly displayName: string; readonly canDecide: boolean }
export interface RiskModel { readonly id: string; readonly number: string; readonly type: "Threat" | "Opportunity"; readonly cause: string; readonly uncertainEvent: string; readonly impactStatement: string; readonly category: string; readonly ownerUserId: string; readonly ownerDisplayName: string; readonly confidentiality: Confidentiality; readonly status: RiskStatus; readonly probability: string | null; readonly inherentScore: number | null; readonly inherentRating: string | null; readonly residualScore: number | null; readonly residualRating: string | null; readonly matrixVersionId: string | null; readonly matrixVersion: number | null; readonly responseStrategy: string | null; readonly responsePlan: string | null; readonly earlyWarningIndicator: string | null; readonly reviewDate: string | null; readonly evidenceReferences: readonly string[]; readonly materializedIssueId: string | null; readonly slaDueAt: string | null; readonly createdAt: string; readonly revision: number }
export interface IssueModel { readonly id: string; readonly number: string; readonly title: string; readonly observedFact: string; readonly category: string; readonly severity: Severity; readonly urgency: Urgency; readonly ownerUserId: string; readonly ownerDisplayName: string; readonly targetResolutionDate: string; readonly confidentiality: Confidentiality; readonly status: IssueStatus; readonly materializedFromRiskId: string | null; readonly evidenceReferences: readonly string[]; readonly slaDueAt: string | null; readonly resolutionNote: string | null; readonly closureEvidence: readonly string[]; readonly resolvedBy: string | null; readonly resolvedAt: string | null; readonly closedBy: string | null; readonly closedAt: string | null; readonly createdAt: string; readonly revision: number }
export interface DecisionRequestModel { readonly id: string; readonly number: string; readonly question: string; readonly whyNow: string; readonly requiredBy: string; readonly authorityUserId: string; readonly authorityDisplayName: string; readonly knownFacts: readonly string[]; readonly assumptions: readonly string[]; readonly predictions: readonly string[]; readonly options: readonly string[]; readonly recommendation: string | null; readonly constraints: readonly string[]; readonly evidenceReferences: readonly string[]; readonly confidentiality: Confidentiality; readonly status: DecisionRequestStatus; readonly informationRequest: string | null; readonly decisionRecordId: string | null; readonly slaDueAt: string | null; readonly createdAt: string; readonly revision: number }
export interface DecisionModel { readonly id: string; readonly decisionRequestId: string; readonly number: string; readonly selectedOption: string; readonly rationale: string; readonly conditions: readonly string[]; readonly channel: string; readonly decidedAt: string; readonly effectiveDate: string | null; readonly decidedBy: string; readonly decidedByDisplayName: string; readonly supersedesDecisionId: string | null; readonly supersededByDecisionId: string | null; readonly effectReview: string | null; readonly effectEvidence: readonly string[]; readonly status: string; readonly recordedAt: string; readonly revision: number }
export interface EscalationModel { readonly id: string; readonly entityType: string; readonly entityId: string; readonly entityNumber: string; readonly entityTitle: string; readonly reason: string; readonly level: number; readonly recipientUserId: string; readonly recipientDisplayName: string; readonly confidentiality: Confidentiality; readonly status: "Open" | "Acknowledged" | "ClosedBySourceResolution"; readonly occurrenceCount: number; readonly firstRaisedAt: string; readonly lastRaisedAt: string; readonly acknowledgementNote: string | null; readonly revision: number }
export interface DeadlineAlertModel { readonly entityType: string; readonly entityId: string; readonly entityNumber: string; readonly title: string; readonly deadlineKind: string; readonly dueAt: string; readonly signal: DeadlineSignal; readonly confidentiality: Confidentiality }
export interface GovernanceStateModel { readonly setupState: "SetupRequired" | "Configured"; readonly sensitiveRecordsIncluded: boolean; readonly assignablePeople: readonly GovernancePersonModel[]; readonly riskMatrices: readonly RiskMatrixModel[]; readonly slaRules: readonly SlaRuleModel[]; readonly risks: readonly RiskModel[]; readonly issues: readonly IssueModel[]; readonly decisionRequests: readonly DecisionRequestModel[]; readonly decisions: readonly DecisionModel[]; readonly escalations: readonly EscalationModel[]; readonly alerts: readonly DeadlineAlertModel[]; readonly counts: { readonly openIssues: number; readonly activeRisks: number; readonly criticalRisks: number; readonly pendingDecisions: number; readonly unacknowledgedEscalations: number }; readonly outlook: { readonly state: "Available" | "InsufficientData"; readonly trackedDeadlines: number; readonly dueWithinSevenDays: number; readonly overdue: number; readonly calculatedAt: string } }

export const getGovernanceState = (baseUrl: string, identity: GovernanceIdentity, projectId: string) =>
  request<GovernanceStateModel>(path(baseUrl, projectId, "/"), identity);
export const createRiskMatrix = (baseUrl: string, identity: GovernanceIdentity, projectId: string, input: { title: string; lowMaximum: number; moderateMaximum: number; highMaximum: number; effectiveFrom: string }) =>
  command<RiskMatrixModel>(path(baseUrl, projectId, "/settings/risk-matrices"), identity, { clientGeneratedId: crypto.randomUUID(), ...input });
export const createSlaRule = (baseUrl: string, identity: GovernanceIdentity, projectId: string, input: { title: string; entityType: SlaRuleModel["entityType"]; severity: Severity | null; duration: number; durationUnit: SlaRuleModel["durationUnit"]; warningLeadMinutes: number; escalationDelayMinutes: number; escalationRecipientUserId: string; effectiveFrom: string }) =>
  command<SlaRuleModel>(path(baseUrl, projectId, "/settings/sla-rules"), identity, { clientGeneratedId: crypto.randomUUID(), ...input });
export const createIssue = (baseUrl: string, identity: GovernanceIdentity, projectId: string, input: { title: string; observedFact: string; category: string; severity: Severity; urgency: Urgency; ownerUserId: string; targetResolutionDate: string; sourceModule: string; sourceEntityType: string; sourceSnapshot: string; evidenceReferences: readonly string[]; confidentiality: Confidentiality }) =>
  command<IssueModel>(path(baseUrl, projectId, "/issues"), identity, { clientGeneratedId: crypto.randomUUID(), sourceEntityId: null, sourceRevision: null, ...input });
export const transitionIssue = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: IssueModel, targetStatus: IssueStatus, resolutionNote?: string, closureEvidenceReferences: readonly string[] = []) =>
  command<IssueModel>(path(baseUrl, projectId, `/issues/${item.id}/transition`), identity, { baseRevision: item.revision, targetStatus, resolutionNote: optional(resolutionNote), closureEvidenceReferences });
export const proposeRisk = (baseUrl: string, identity: GovernanceIdentity, projectId: string, input: { type: "Threat" | "Opportunity"; cause: string; uncertainEvent: string; impactStatement: string; category: string; ownerUserId: string; confidentiality: Confidentiality; sourceModule: string; sourceEntityType: string; sourceSnapshot: string; evidenceReferences: readonly string[] }) =>
  command<RiskModel>(path(baseUrl, projectId, "/risks"), identity, { clientGeneratedId: crypto.randomUUID(), sourceEntityId: null, sourceRevision: null, ...input });
export const assessRisk = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: RiskModel, input: { matrixVersionId: string; probability: string; impact: string; responseStrategy: string; responsePlan: string; earlyWarningIndicator: string; reviewDate: string }) =>
  command<RiskModel>(path(baseUrl, projectId, `/risks/${item.id}/assess`), identity, { baseRevision: item.revision, matrixVersionId: input.matrixVersionId, probability: input.probability, timeImpact: input.impact, costImpact: input.impact, qualityImpact: input.impact, safetyImpact: input.impact, contractImpact: input.impact, operationsImpact: input.impact, responseStrategy: input.responseStrategy, responsePlan: input.responsePlan, earlyWarningIndicator: input.earlyWarningIndicator, reviewDate: input.reviewDate });
export const activateRisk = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: RiskModel) =>
  command<RiskModel>(path(baseUrl, projectId, `/risks/${item.id}/activate`), identity, { baseRevision: item.revision });
export const reviewRisk = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: RiskModel, input: { residualProbability: string; residualImpact: string; responsePlan: string; nextReviewDate: string }) =>
  command<RiskModel>(path(baseUrl, projectId, `/risks/${item.id}/review`), identity, { baseRevision: item.revision, ...input });
export const closeRisk = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: RiskModel, reason: string, evidenceReferences: readonly string[], expired = false) =>
  command<RiskModel>(path(baseUrl, projectId, `/risks/${item.id}/close`), identity, { baseRevision: item.revision, expired, reason, evidenceReferences });
export const materializeRisk = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: RiskModel, input: { title: string; observedFact: string; category: string; severity: Severity; urgency: "Routine" | "Soon" | "Immediate"; ownerUserId: string; targetResolutionDate: string; evidenceReferences: readonly string[] }) =>
  command<{ risk: RiskModel; issue: IssueModel }>(path(baseUrl, projectId, `/risks/${item.id}/materialize`), identity, { baseRevision: item.revision, issueId: crypto.randomUUID(), ...input });
export const createDecisionRequest = (baseUrl: string, identity: GovernanceIdentity, projectId: string, input: { question: string; whyNow: string; requiredBy: string; authorityUserId: string; knownFacts: readonly string[]; assumptions: readonly string[]; predictions: readonly string[]; options: readonly string[]; recommendation?: string; constraints: readonly string[]; evidenceReferences: readonly string[]; confidentiality: Confidentiality; sourceModule: string; sourceEntityType: string; sourceSnapshot: string }) =>
  command<DecisionRequestModel>(path(baseUrl, projectId, "/decision-requests"), identity, { clientGeneratedId: crypto.randomUUID(), sourceEntityId: null, sourceRevision: null, ...input, recommendation: optional(input.recommendation) });
export const submitDecisionRequest = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: DecisionRequestModel) =>
  command<DecisionRequestModel>(path(baseUrl, projectId, `/decision-requests/${item.id}/submit`), identity, { baseRevision: item.revision, informationRequest: null });
export const beginDecision = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: DecisionRequestModel) =>
  command<DecisionRequestModel>(path(baseUrl, projectId, `/decision-requests/${item.id}/begin`), identity, { baseRevision: item.revision, informationRequest: null });
export const markDecisionImplementing = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: DecisionRequestModel) =>
  command<DecisionRequestModel>(path(baseUrl, projectId, `/decision-requests/${item.id}/implement`), identity, { baseRevision: item.revision, informationRequest: null });
export const recordDecision = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: DecisionRequestModel, selectedOption: string, rationale: string) =>
  command<{ request: DecisionRequestModel; decision: DecisionModel }>(path(baseUrl, projectId, `/decision-requests/${item.id}/decisions`), identity, { clientGeneratedId: crypto.randomUUID(), baseRevision: item.revision, selectedOption, rationale, conditions: [], channel: "InSystem", decidedAt: new Date().toISOString(), effectiveDate: null });
export const evaluateGovernance = (baseUrl: string, identity: GovernanceIdentity, projectId: string) =>
  command<{ raised: number; refreshed: number; closed: number; escalations: readonly EscalationModel[] }>(path(baseUrl, projectId, "/alerts/evaluate"), identity, {});
export const acknowledgeEscalation = (baseUrl: string, identity: GovernanceIdentity, projectId: string, item: EscalationModel, note?: string) =>
  command<EscalationModel>(path(baseUrl, projectId, `/escalations/${item.id}/acknowledge`), identity, { baseRevision: item.revision, note: optional(note) });

async function command<T>(url: string, identity: GovernanceIdentity, body: unknown): Promise<T> {
  return request<T>(url, identity, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(body) });
}
async function request<T>(url: string, identity: GovernanceIdentity, init: RequestInit = {}): Promise<T> {
  const response = await fetch(url, { ...init, headers: { "X-Tenant-Id": identity.tenantId, "X-User-Id": identity.userId, ...init.headers } });
  await ensureApiSuccess(response); return response.json() as Promise<T>;
}
function path(baseUrl: string, projectId: string, suffix: string) { return `${baseUrl.replace(/\/$/u, "")}/api/v1/projects/${projectId}/governance${suffix}`; }
function optional(value?: string) { return value?.trim() ? value.trim() : null; }
